<a href="https://colab.research.google.com/github/iLonow/sii/blob/main/%D0%96%D0%B0%D1%80%D0%B8%D0%BD%D0%BE%D0%B2_%D0%90%D0%BB%D0%B5%D0%BA%D1%81%D0%B0%D0%BD%D0%B4%D1%80_%D0%A0%D0%A27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Задание 1: Нейронные сети, Реализация нейронной сети на Python и Обучение нейронной сети**

Условие 1.1: Реализовать классы нейросетей по аналогии с классом OurNeuralNetwork.
Данные нейросети:

− три входа (𝑥1, 𝑥2, 𝑥3);

− три нейрона в скрытых слоях (ℎ1, ℎ2, ℎ3);

− выход (𝑜1).

Нейроны имеют идентичные веса и пороги:

− 𝑤 = [0.5, 0.5, 0.5]

− 𝑏 = 0

Данные нейросети:

− два входа (𝑥1, 𝑥2);

− два нейрона в скрытых слоях (ℎ1, ℎ2);

− два выхода (𝑜1, 𝑜2).

Нейроны имеют идентичные веса и пороги:

− 𝑤 = [1, 0];

− 𝑏 = 1.

In [ ]:
import numpy as np

class OurNeuralNetwork1:
    def __init__(self):
        self.weights = np.array([0.5, 0.5, 0.5])
        self.bias = 0

    def feedforward(self, x1, x2, x3):
        sum = np.dot(self.weights, np.array([x1, x2, x3])) + self.bias
        return self.sigmoid(sum)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

class OurNeuralNetwork2:
    def __init__(self):
        self.weights = np.array([1, 0])
        self.bias = 1

    def feedforward(self, x1, x2):
        sum = np.dot(self.weights, np.array([x1, x2])) + self.bias
        return self.sigmoid(sum)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

network1 = OurNeuralNetwork1()
network2 = OurNeuralNetwork2()
print("Первая нейросеть")
print(network1.feedforward(0, 10, 100))
print("Вторая нейросеть")
print(network2.feedforward(0, 10))
print(network2.feedforward(0, 20))

Первая нейросеть
1.0
Вторая нейросеть
0.7310585786300049
0.7310585786300049


Условие 1.2: Реализуйте классы нейронных сетей с использованием других функций активации.

In [ ]:
import numpy as np

class OurNeuralNetwork1:
    def __init__(self):
        self.weights = np.array([0.5, 0.5, 0.5])
        self.bias = 0

    def feedforward(self, x1, x2, x3):
        sum = np.dot(self.weights, np.array([x1, x2, x3])) + self.bias
        return self.sigmoid(sum)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

class OurNeuralNetwork2:
    def __init__(self):
        self.weights = np.array([1, 0])
        self.bias = 1

    def feedforward(self, x1, x2):
        sum = np.dot(self.weights, np.array([x1, x2])) + self.bias
        return self.sigmoid(sum)

    def sigmoid(self, x):
        return 1 / (1 + np.exp(-x))

network1 = OurNeuralNetwork1()
network2 = OurNeuralNetwork2()
print("Первая нейросеть")
print(network1.feedforward(0, 10, 100))
print("Вторая нейросеть")
print(network2.feedforward(0, 10))
print(network2.feedforward(0, 20))

Первая нейросеть
1.0
Вторая нейросеть
0.7310585786300049
0.7310585786300049


In [ ]:
import numpy as np

class OurNeuralNetwork:
    def __init__(self):
        self.weights = np.array([0.5, 0.5, 0.5])
        self.bias = 0

    def feedforward(self, x1, x2, x3):
        sum = np.dot(self.weights, np.array([x1, x2, x3])) + self.bias
        return self.tanh(sum)

    def tanh(self, x):
        return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

class OurNeuralNetwork2:
    def __init__(self):
        self.weights = np.array([1, 0])
        self.bias = 1

    def feedforward(self, x1, x2):
        sum = np.dot(self.weights, np.array([x1, x2])) + self.bias
        return self.tanh(sum)

    def tanh(self, x):
        return (np.exp(x) - np.exp(-x)) / (np.exp(x) + np.exp(-x))

network = OurNeuralNetwork()
network2 = OurNeuralNetwork2()
print("Первая нейросеть")
print(network.feedforward(0, 10, 100))
print("Вторая нейросеть")
print(network2.feedforward(0, 10))
print(network2.feedforward(0, 20))

Первая нейросеть
1.0
Вторая нейросеть
0.7615941559557649
0.7615941559557649


In [ ]:
import numpy as np

class OurNeuralNetwork1:
    def __init__(self):
        self.weights = np.array([0.5, 0.5, 0.5])
        self.bias = 0

    def feedforward(self, x1, x2, x3):
        sum = np.dot(self.weights, np.array([x1, x2, x3])) + self.bias
        return self.relu(sum)

    def relu(self, x):
        return np.maximum(0, x)

class OurNeuralNetwork2:
    def __init__(self):
        self.weights = np.array([1, 0])
        self.bias = 1

    def feedforward(self, x1, x2):
        sum = np.dot(self.weights, np.array([x1, x2])) + self.bias
        return self.relu(sum)

    def relu(self, x):
        return np.maximum(0, x)

network1 = OurNeuralNetwork1()
network2 = OurNeuralNetwork2()
print("Первая нейросеть")
print(network1.feedforward(0, 10, 100))
print("Вторая нейросеть")
print(network2.feedforward(0, 10))
print(network2.feedforward(0, 20))

Первая нейросеть
55.0
Вторая нейросеть
1
1


**Задание 2: Введение в нейронные сети с помощью Scikit-Learn в Python, MLPClassifier и MLPRegressor**

Условие: Используйте классы MLPClassified и MLPRegressor для классификации и
регрессии произвольных данных из интернета. Проведите анализ атрибуты, полученных моделей.

Для классификации можете взять набор данных Ирисов:
https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv
а для регрессии датасет зависимости заработной платы от опыта работы:
https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linear-regression/master/Salary_Data.csv

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import confusion_matrix

url = r'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
dataset = pd.read_csv(url)

X = dataset.iloc[:, :-1].values
Y = dataset.iloc[:, -1].values
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, train_size = 0.80, test_size = 0.20, stratify = Y, random_state = 123)

mlp_classifier = MLPClassifier(max_iter = 1000).fit(X_train, Y_train)
Y_pred = mlp_classifier.predict(X_test)

df = pd.DataFrame({'Actual': Y_test, 'Predicted': Y_pred})
print(df)

print("\nTest Accuracy: %.3f"%mlp_classifier.score(X_test, Y_test))
print('Training Accuracy: %.3f'%mlp_classifier.score(X_train, Y_train))
print(f"\nMatrix of Confusion:\n {confusion_matrix(Y_test, Y_pred)}")
print(f"\nLoss : ", mlp_classifier.loss_)
print(f'Number of Coefs : ', len(mlp_classifier.coefs_))
print(f'Number of Intercepts : ', len(mlp_classifier.intercepts_))
print(f'Number of Iterations for Which Estimator Run : ', mlp_classifier.n_iter_)
print(f'Name of Output Layer Activation Function : ', mlp_classifier.out_activation_)

        Actual   Predicted
0   Versicolor  Versicolor
1       Setosa      Setosa
2    Virginica   Virginica
3    Virginica   Virginica
4       Setosa      Setosa
5       Setosa      Setosa
6    Virginica   Virginica
7   Versicolor   Virginica
8    Virginica   Virginica
9       Setosa      Setosa
10      Setosa      Setosa
11  Versicolor  Versicolor
12   Virginica   Virginica
13  Versicolor  Versicolor
14   Virginica   Virginica
15  Versicolor  Versicolor
16      Setosa      Setosa
17      Setosa      Setosa
18      Setosa      Setosa
19      Setosa      Setosa
20      Setosa      Setosa
21   Virginica   Virginica
22   Virginica   Virginica
23  Versicolor  Versicolor
24   Virginica   Virginica
25   Virginica   Virginica
26  Versicolor  Versicolor
27  Versicolor  Versicolor
28  Versicolor   Virginica
29  Versicolor  Versicolor

Test Accuracy: 0.933
Training Accuracy: 0.992

Matrix of Confusion:
 [[10  0  0]
 [ 0  8  2]
 [ 0  0 10]]

Loss :  0.0484543958533654
Number of Coefs :  2
Number 

In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPRegressor

url = r'https://raw.githubusercontent.com/AnnaShestova/salary-years-simple-linear-regression/master/Salary_Data.csv'

ata = pd.read_csv(url)

X_train, X_test, y_train, y_test = train_test_split(
    data.iloc[:,:-1].values,
    data.iloc[:,-1].values,
    test_size = 0.20,
    random_state=123
)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

mlp_regressor = MLPRegressor(random_state=123, max_iter = 32000)
mlp_regressor.fit(X_train, y_train)
Y_preds = mlp_regressor.predict(X_test)

print(Y_preds[:10])
print(y_test[:10])
print('Test R^2: %.3f'%mlp_regressor.score(X_test, y_test))
print('Training R^2: %.3f'%mlp_regressor.score(X_train, y_train))
print("Loss: ", mlp_regressor.loss_)
print("Number of coefs: ", len(mlp_regressor.coefs_))
print("Number of intercepts: ", len(mlp_regressor.intercepts_))
print("Number of iterations for which estimator ran: ", mlp_regressor.n_iter_)
print("Name of output layer activation function: ", mlp_regressor.out_activation_)

(24, 1) (6, 1) (24,) (6,)
[ 55265.2045971  126554.5591937   52335.80522199 116782.59147446
  55265.2045971  117759.05793283]
[ 54445. 121872.  56642. 116969.  64445. 112635.]
Test R^2: 0.971
Training R^2: 0.948
Loss:  16873681.689960103
Number of coefs:  2
Number of intercepts:  2
Number of iterations for which estimator ran:  30344
Name of output layer activation function:  identity
